import { StyleSheet } from "react-native";

import { palette } from "./schedule";

export const navigationStyles = StyleSheet.create({
  headerInboxButton: {
    alignItems: "center",
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 999,
    borderWidth: 1,
    marginRight: 12,
    minHeight: 34,
    gap: 6,
    paddingHorizontal: 12,
    justifyContent: "center",
    flexDirection: "row",
  },
  headerInboxButtonText: {
    color: palette.accent,
    fontWeight: "700",
  },
  overlay: {
    alignItems: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 72,
  },
  inboxPanel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    maxHeight: "78%",
    padding: 12,
    width: "92%",
  },
  panelHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 10,
  },
  panelTitle: {
    color: "#151515",
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
  },
  closeButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  closeButtonText: {
    color: "#2f2f2b",
    fontWeight: "700",
  },
  loadingBox: {
    alignItems: "center",
    gap: 8,
    padding: 22,
  },
  loadingText: {
    color: "#666",
  },
  errorText: {
    color: "#b42318",
    paddingVertical: 12,
  },
  emptyText: {
    color: "#6a6a64",
    paddingVertical: 12,
  },
  latestList: {
    gap: 8,
  },
  latestItem: {
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 10,
  },
  latestItemUnread: {
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  latestTopRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  latestTitle: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
  },
  latestState: {
    fontSize: 12,
    fontWeight: "700",
  },
  latestStateUnread: {
    fontWeight: "800",
  },
  latestMeta: {
    color: "#64645e",
    fontSize: 12,
  },
  latestPreview: {
    color: "#393934",
    fontSize: 13,
    lineHeight: 18,
  },
  viewAllButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    marginTop: 12,
    paddingVertical: 11,
  },
  viewAllText: {
    color: "#fff",
    fontWeight: "700",
  },
  detailOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "flex-end",
  },
  detailPanel: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: "86%",
  },
  detailContent: {
    gap: 12,
    padding: 16,
    paddingBottom: 28,
  },
  detailTitle: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
  },
  detailMeta: {
    color: "#62625c",
    fontSize: 14,
  },
  detailBody: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  detailText: {
    color: "#222",
    fontSize: 16,
    lineHeight: 23,
  },
});

export const drawerStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingBottom: 18,
  },
  topBlock: {
    gap: 14,
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  brandRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  brandMark: {
    alignItems: "center",
    backgroundColor: palette.accentSoft,
    borderRadius: 16,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  brandMarkText: {
    color: palette.accent,
    fontSize: 20,
    fontWeight: "900",
  },
  brandCopy: {
    flex: 1,
  },
  brandTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "900",
  },
  brandSubtitle: {
    color: palette.muted,
    fontSize: 12,
    marginTop: 2,
  },
  menuBlock: {
    gap: 8,
  },
  item: {
    alignItems: "center",
    borderRadius: 16,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  itemActive: {
    backgroundColor: palette.accent,
  },
  itemPressed: {
    backgroundColor: palette.accentSoft,
  },
  itemText: {
    color: palette.text,
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
  },
  itemTextActive: {
    color: "#fff",
  },
  advancedBlock: {
    borderTopColor: palette.border,
    borderTopWidth: 1,
    marginTop: 4,
    paddingTop: 10,
  },
  advancedToggle: {
    alignItems: "center",
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  advancedLabel: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "800",
  },
  advancedList: {
    gap: 8,
    paddingLeft: 0,
    paddingTop: 8,
  },
  logoutButton: {
    alignItems: "center",
    backgroundColor: palette.danger,
    borderRadius: 18,
    flexDirection: "row",
    gap: 10,
    marginHorizontal: 16,
    marginTop: "auto",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  logoutButtonPressed: {
    backgroundColor: "#8f1c13",
  },
  logoutText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
  },
});

export const organizationStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#eef3ff",
  },
  content: {
    gap: 14,
    padding: 16,
  },
  title: {
    color: "#151515",
    fontSize: 24,
    fontWeight: "700",
  },
  subtitle: {
    color: "#62625c",
    marginTop: -8,
  },
  panel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  grid: {
    gap: 10,
  },
  field: {
    gap: 6,
  },
  label: {
    color: "#595952",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#151515",
    minHeight: 44,
    paddingHorizontal: 12,
  },
  actions: {
    gap: 8,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    minHeight: 46,
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#5f6df5",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  disabledButton: {
    opacity: 0.65,
  },
  muted: {
    color: "#62625c",
  },
  successText: {
    color: "#217a3f",
  },
  errorText: {
    color: "#b42318",
  },
});

export const administrationStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 104,
  },
  searchPanel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  title: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
  },
  searchRow: {
    flexDirection: "row",
    gap: 10,
  },
  input: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#1f1f1d",
    flex: 1,
    fontSize: 16,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  submitButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    justifyContent: "center",
    minWidth: 88,
    paddingHorizontal: 14,
  },
  submitButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  loading: {
    alignItems: "center",
    gap: 8,
    padding: 28,
  },
  loadingText: {
    color: "#666",
  },
  empty: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 24,
  },
  emptyTitle: {
    color: "#1f1f1d",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  emptyDetail: {
    color: "#6a6a64",
    textAlign: "center",
  },
  groupsList: {
    gap: 10,
  },
  groupCard: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  groupHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  groupName: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
  },
  groupCount: {
    backgroundColor: "#e4e7ff",
    borderRadius: 8,
    color: "#5f6df5",
    fontWeight: "700",
    minWidth: 36,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    textAlign: "center",
  },
  categoryActionButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  categoryActionText: {
    color: "#5f6df5",
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 22,
  },
  groupEmpty: {
    borderTopColor: "#e8ecff",
    borderTopWidth: 1,
    color: "#6a6a64",
    padding: 14,
  },
  userList: {
    borderTopColor: "#e8ecff",
    borderTopWidth: 1,
  },
  userRow: {
    alignItems: "center",
    borderBottomColor: "#f0f0ec",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  avatar: {
    backgroundColor: "#e4e7ff",
    borderRadius: 20,
    height: 40,
    width: 40,
  },
  userName: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    minWidth: 0,
  },
  userRole: {
    color: "#5f6df5",
    fontSize: 12,
    fontWeight: "700",
    minWidth: 62,
    textAlign: "right",
  },
  modalOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: "88%",
  },
  modalContent: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  xButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  xButtonText: {
    color: "#2f2f2b",
    fontWeight: "700",
  },
  previewHeader: {
    alignItems: "center",
    gap: 8,
  },
  previewAvatar: {
    backgroundColor: "#e4e7ff",
    borderRadius: 48,
    height: 96,
    width: 96,
  },
  previewName: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
    textAlign: "center",
  },
  previewRole: {
    color: "#676760",
    fontSize: 15,
  },
  detailsPanel: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
  },
  detailRow: {
    borderBottomColor: "#e8ecff",
    borderBottomWidth: 1,
    gap: 4,
    padding: 12,
  },
  detailLabel: {
    color: "#6a6a64",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  detailValue: {
    color: "#222",
    fontSize: 16,
  },
  editPanel: {
    gap: 12,
  },
  field: {
    gap: 6,
  },
  fieldLabel: {
    color: "#4c4c47",
    fontSize: 13,
    fontWeight: "700",
  },
  fieldError: {
    color: "#b42318",
    fontSize: 12,
  },
  editInput: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#1f1f1d",
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dateButton: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 12,
  },
  dateButtonText: {
    color: "#1f1f1d",
    fontSize: 16,
  },
  datePlaceholder: {
    color: "#777",
  },
  selectButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 46,
    paddingHorizontal: 12,
  },
  selectButtonText: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 16,
  },
  selectArrow: {
    color: "#64645e",
    fontSize: 12,
    fontWeight: "700",
  },
  optionsOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  optionsBox: {
    backgroundColor: "#fff",
    borderRadius: 8,
    maxHeight: "70%",
    overflow: "hidden",
    width: "100%",
  },
  option: {
    borderBottomColor: "#e8ecff",
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  optionRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  optionText: {
    color: "#1f1f1d",
    fontSize: 16,
  },
  formError: {
    color: "#b42318",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
  },
  editButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  editButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  deleteButton: {
    alignItems: "center",
    backgroundColor: "#b42318",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  deleteButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  cancelButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 12,
  },
  cancelButtonText: {
    color: "#3d3d39",
    fontWeight: "700",
  },
  saveButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  fabContainer: {
    alignItems: "flex-end",
    bottom: 24,
    gap: 10,
    position: "absolute",
    right: 16,
  },
  fabMenu: {
    gap: 8,
  },
  fabMenuButton: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 112,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  fabMenuText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  fab: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    elevation: 4,
    minWidth: 112,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: "#000",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },
  fabText: {
    color: "#fff",
    fontWeight: "700",
  },
});

export const screenSharedStyles = StyleSheet.create({
  emptyState: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 20,
  },
  emptyStateDashed: {
    borderStyle: "dashed",
  },
  emptyStateTitle: {
    color: "#1f1f1d",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  emptyStateDetail: {
    color: "#6a6a64",
    textAlign: "center",
  },
  fieldButton: {
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    minHeight: 68,
    justifyContent: "center",
    paddingHorizontal: 12,
    backgroundColor: palette.backgroundSoft,
  },
  fieldLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  fieldValue: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "800",
  },
});
