import { StyleSheet } from "react-native";

import { palette } from "./schedule";

export const navigationStyles = StyleSheet.create({
  headerInboxButton: {
    alignItems: "center",
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 999,
    borderWidth: 1,
    marginRight: 12,
    minHeight: 34,
    gap: 6,
    paddingHorizontal: 12,
    justifyContent: "center",
    flexDirection: "row",
  },
  headerInboxButtonText: {
    color: palette.accent,
    fontWeight: "700",
  },
  overlay: {
    alignItems: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 72,
  },
  inboxPanel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    maxHeight: "78%",
    padding: 12,
    width: "92%",
  },
  panelHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 10,
  },
  panelTitle: {
    color: "#151515",
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
  },
  closeButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  closeButtonText: {
    color: "#2f2f2b",
    fontWeight: "700",
  },
  loadingBox: {
    alignItems: "center",
    gap: 8,
    padding: 22,
  },
  loadingText: {
    color: "#666",
  },
  errorText: {
    color: "#b42318",
    paddingVertical: 12,
  },
  emptyText: {
    color: "#6a6a64",
    paddingVertical: 12,
  },
  latestList: {
    gap: 8,
  },
  latestItem: {
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 10,
  },
  latestItemUnread: {
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  latestTopRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  latestTitle: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
  },
  latestState: {
    fontSize: 12,
    fontWeight: "700",
  },
  latestStateUnread: {
    fontWeight: "800",
  },
  latestMeta: {
    color: "#64645e",
    fontSize: 12,
  },
  latestPreview: {
    color: "#393934",
    fontSize: 13,
    lineHeight: 18,
  },
  viewAllButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    marginTop: 12,
    paddingVertical: 11,
  },
  viewAllText: {
    color: "#fff",
    fontWeight: "700",
  },
  detailOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "flex-end",
  },
  detailPanel: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: "86%",
  },
  detailContent: {
    gap: 12,
    padding: 16,
    paddingBottom: 28,
  },
  detailTitle: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
  },
  detailMeta: {
    color: "#62625c",
    fontSize: 14,
  },
  detailBody: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  detailText: {
    color: "#222",
    fontSize: 16,
    lineHeight: 23,
  },
});

export const drawerStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingBottom: 18,
  },
  topBlock: {
    gap: 14,
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  brandRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  brandMark: {
    alignItems: "center",
    backgroundColor: palette.accentSoft,
    borderRadius: 16,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  brandMarkText: {
    color: palette.accent,
    fontSize: 20,
    fontWeight: "900",
  },
  brandCopy: {
    flex: 1,
  },
  brandTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "900",
  },
  brandSubtitle: {
    color: palette.muted,
    fontSize: 12,
    marginTop: 2,
  },
  menuBlock: {
    gap: 8,
  },
  item: {
    alignItems: "center",
    borderRadius: 16,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  itemActive: {
    backgroundColor: palette.accent,
  },
  itemPressed: {
    backgroundColor: palette.accentSoft,
  },
  itemText: {
    color: palette.text,
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
  },
  itemTextActive: {
    color: "#fff",
  },
  advancedBlock: {
    borderTopColor: palette.border,
    borderTopWidth: 1,
    marginTop: 4,
    paddingTop: 10,
  },
  advancedToggle: {
    alignItems: "center",
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  advancedLabel: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "800",
  },
  advancedList: {
    gap: 8,
    paddingLeft: 0,
    paddingTop: 8,
  },
  logoutButton: {
    alignItems: "center",
    backgroundColor: palette.danger,
    borderRadius: 18,
    flexDirection: "row",
    gap: 10,
    marginHorizontal: 16,
    marginTop: "auto",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  logoutButtonPressed: {
    backgroundColor: "#8f1c13",
  },
  logoutText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
  },
});

export const organizationStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#eef3ff",
  },
  content: {
    gap: 14,
    padding: 16,
  },
  title: {
    color: "#151515",
    fontSize: 24,
    fontWeight: "700",
  },
  subtitle: {
    color: "#62625c",
    marginTop: -8,
  },
  panel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  grid: {
    gap: 10,
  },
  field: {
    gap: 6,
  },
  label: {
    color: "#595952",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#151515",
    minHeight: 44,
    paddingHorizontal: 12,
  },
  actions: {
    gap: 8,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    minHeight: 46,
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#5f6df5",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  disabledButton: {
    opacity: 0.65,
  },
  muted: {
    color: "#62625c",
  },
  successText: {
    color: "#217a3f",
  },
  errorText: {
    color: "#b42318",
  },
});

export const administrationStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 104,
  },
  searchPanel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  title: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
  },
  searchRow: {
    flexDirection: "row",
    gap: 10,
  },
  input: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#1f1f1d",
    flex: 1,
    fontSize: 16,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  submitButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    justifyContent: "center",
    minWidth: 88,
    paddingHorizontal: 14,
  },
  submitButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  loading: {
    alignItems: "center",
    gap: 8,
    padding: 28,
  },
  loadingText: {
    color: "#666",
  },
  empty: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 24,
  },
  emptyTitle: {
    color: "#1f1f1d",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  emptyDetail: {
    color: "#6a6a64",
    textAlign: "center",
  },
  groupsList: {
    gap: 10,
  },
  groupCard: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  groupHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  groupName: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
  },
  groupCount: {
    backgroundColor: "#e4e7ff",
    borderRadius: 8,
    color: "#5f6df5",
    fontWeight: "700",
    minWidth: 36,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    textAlign: "center",
  },
  categoryActionButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  categoryActionText: {
    color: "#5f6df5",
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 22,
  },
  groupEmpty: {
    borderTopColor: "#e8ecff",
    borderTopWidth: 1,
    color: "#6a6a64",
    padding: 14,
  },
  userList: {
    borderTopColor: "#e8ecff",
    borderTopWidth: 1,
  },
  userRow: {
    alignItems: "center",
    borderBottomColor: "#f0f0ec",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  avatar: {
    backgroundColor: "#e4e7ff",
    borderRadius: 20,
    height: 40,
    width: 40,
  },
  userName: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    minWidth: 0,
  },
  userRole: {
    color: "#5f6df5",
    fontSize: 12,
    fontWeight: "700",
    minWidth: 62,
    textAlign: "right",
  },
  modalOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: "88%",
  },
  modalContent: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  xButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  xButtonText: {
    color: "#2f2f2b",
    fontWeight: "700",
  },
  previewHeader: {
    alignItems: "center",
    gap: 8,
  },
  previewAvatar: {
    backgroundColor: "#e4e7ff",
    borderRadius: 48,
    height: 96,
    width: 96,
  },
  previewName: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
    textAlign: "center",
  },
  previewRole: {
    color: "#676760",
    fontSize: 15,
  },
  detailsPanel: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
  },
  detailRow: {
    borderBottomColor: "#e8ecff",
    borderBottomWidth: 1,
    gap: 4,
    padding: 12,
  },
  detailLabel: {
    color: "#6a6a64",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  detailValue: {
    color: "#222",
    fontSize: 16,
  },
  editPanel: {
    gap: 12,
  },
  field: {
    gap: 6,
  },
  fieldLabel: {
    color: "#4c4c47",
    fontSize: 13,
    fontWeight: "700",
  },
  fieldError: {
    color: "#b42318",
    fontSize: 12,
  },
  editInput: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#1f1f1d",
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dateButton: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 12,
  },
  dateButtonText: {
    color: "#1f1f1d",
    fontSize: 16,
  },
  datePlaceholder: {
    color: "#777",
  },
  selectButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 46,
    paddingHorizontal: 12,
  },
  selectButtonText: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 16,
  },
  selectArrow: {
    color: "#64645e",
    fontSize: 12,
    fontWeight: "700",
  },
  optionsOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  optionsBox: {
    backgroundColor: "#fff",
    borderRadius: 8,
    maxHeight: "70%",
    overflow: "hidden",
    width: "100%",
  },
  option: {
    borderBottomColor: "#e8ecff",
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  optionRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  optionText: {
    color: "#1f1f1d",
    fontSize: 16,
  },
  formError: {
    color: "#b42318",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
  },
  editButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  editButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  deleteButton: {
    alignItems: "center",
    backgroundColor: "#b42318",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  deleteButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  cancelButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 12,
  },
  cancelButtonText: {
    color: "#3d3d39",
    fontWeight: "700",
  },
  saveButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  fabContainer: {
    alignItems: "flex-end",
    bottom: 24,
    gap: 10,
    position: "absolute",
    right: 16,
  },
  fabMenu: {
    gap: 8,
  },
  fabMenuButton: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 112,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  fabMenuText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  fab: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    elevation: 4,
    minWidth: 112,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: "#000",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },
  fabText: {
    color: "#fff",
    fontWeight: "700",
  },
});

export const screenSharedStyles = StyleSheet.create({
  emptyState: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 20,
  },
  emptyStateDashed: {
    borderStyle: "dashed",
  },
  emptyStateTitle: {
    color: "#1f1f1d",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  emptyStateDetail: {
    color: "#6a6a64",
    textAlign: "center",
  },
  fieldButton: {
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    minHeight: 68,
    justifyContent: "center",
    paddingHorizontal: 12,
    backgroundColor: palette.backgroundSoft,
  },
  fieldLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  fieldValue: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "800",
  },
  infoRow: {
    borderTopColor: "#e8ecff",
    borderTopWidth: 1,
    gap: 4,
    paddingVertical: 10,
  },
  infoLabel: {
    color: "#6a6a64",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  infoValue: {
    color: "#222",
    fontSize: 16,
  },
  fieldBlock: {
    gap: 6,
  },
  textInput: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#1f1f1d",
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dateFieldButton: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 12,
  },
  dateFieldText: {
    color: "#1f1f1d",
    fontSize: 16,
  },
  dateFieldPlaceholder: {
    color: "#777",
  },
  fieldError: {
    color: "#b42318",
    fontSize: 12,
  },
  calendarDayCell: {
    alignItems: "center",
    justifyContent: "center",
    aspectRatio: 1,
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "13.0%",
    margin: 2,
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderWidth: 1,
    borderRadius: 16,
  },
  calendarDayCellMuted: {
    opacity: 0.5,
  },
  calendarDayCellSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  calendarDayNumber: {
    color: palette.text,
    fontWeight: "800",
  },
  calendarDayNumberMuted: {
    color: palette.muted,
  },
  calendarDayNumberSelected: {
    color: "#fff",
  },
  calendarDayHint: {
    color: palette.muted,
    fontSize: 11,
    marginTop: 2,
  },
  calendarDayHintSelected: {
    color: "#e7f4f1",
  },
});

export const planSchedulesStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  screen: {
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 110,
  },
  hero: {
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  kicker: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: palette.text,
    fontSize: 26,
    fontWeight: "800",
  },
  heroSubtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  panel: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 22,
    borderWidth: 1,
    padding: 14,
  },
  panelSoft: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  headerCenter: {
    flex: 1,
    gap: 8,
    marginHorizontal: 8,
  },
  selectorButton: {
    alignItems: "center",
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  selectorLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  selectorValue: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  quickRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  quickButton: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 14,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 14,
  },
  quickButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
  quickStat: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 12,
  },
  quickStatValue: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  quickStatLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  dayPreviewRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 3,
    justifyContent: "center",
    marginTop: 4,
  },
  dayPreviewDot: {
    borderRadius: 999,
    height: 6,
    width: 6,
  },
  dayMore: {
    color: palette.muted,
    fontSize: 9,
    fontWeight: "800",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
  },
  sectionActions: {
    alignItems: "flex-end",
    gap: 6,
  },
  sectionHint: {
    color: palette.muted,
    fontSize: 12,
  },
  publishDayButton: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderColor: palette.accent,
    borderWidth: 1,
    borderRadius: 999,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  publishDayButtonDisabled: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    opacity: 1,
  },
  publishDayButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },
  publishDayButtonTextDisabled: {
    color: palette.muted,
  },
  shiftList: {
    gap: 10,
  },
  shiftCard: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  shiftHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  shiftIdentity: {
    flex: 1,
    gap: 4,
  },
  shiftUser: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  shiftMeta: {
    color: palette.muted,
    fontSize: 12,
  },
  statusChip: {
    borderRadius: 999,
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  shiftRow: {
    gap: 4,
  },
  shiftLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  shiftValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  detailRow: {
    gap: 4,
  },
  detailLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  detailValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  muted: {
    color: palette.muted,
    lineHeight: 20,
  },
  errorText: {
    color: palette.danger,
    marginTop: 10,
    fontWeight: "700",
  },
  deniedBox: {
    gap: 8,
    padding: 16,
  },
  modalOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.38)",
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 14,
    maxHeight: "78%",
    padding: 16,
    width: "100%",
  },
  modalTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
  },
  fab: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 999,
    bottom: 18,
    elevation: 6,
    minHeight: 54,
    justifyContent: "center",
    paddingHorizontal: 18,
    position: "absolute",
    right: 16,
    shadowColor: "#000",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  fabText: {
    color: "#fff",
    fontWeight: "800",
  },
  sheetOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.38)",
    flex: 1,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: palette.surfaceElevated,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: "92%",
    paddingTop: 8,
  },
  sheetContent: {
    gap: 12,
    padding: 16,
    paddingBottom: 28,
  },
  sheetHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  sheetTitleGroup: {
    flex: 1,
    gap: 4,
  },
  sheetTitle: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "800",
  },
  sheetSubtitle: {
    color: palette.muted,
    lineHeight: 20,
  },
  closeButton: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 12,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  closeButtonText: {
    color: palette.text,
    fontWeight: "700",
  },
  formRow: {
    flexDirection: "row",
    gap: 8,
  },
  publishToggle: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#fff",
    borderColor: palette.border,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  publishToggleActive: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  publishToggleDisabled: {
    opacity: 0.55,
  },
  publishToggleText: {
    color: palette.accent,
    fontWeight: "800",
  },
  publishToggleTextActive: {
    color: "#fff",
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  segmentButton: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 10,
    backgroundColor: "#fff",
  },
  segmentButtonActive: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  segmentText: {
    color: palette.accent,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: "#fff",
  },
  selectorBlock: {
    gap: 10,
  },
  selectionCount: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  list: {
    gap: 8,
  },
  row: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 10,
    backgroundColor: "#fff",
  },
  rowSelected: {
    backgroundColor: "#f7f8ff",
    borderColor: palette.accent,
  },
  categoryRow: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    padding: 10,
    backgroundColor: "#fff",
  },
  categoryRowSelected: {
    backgroundColor: "#f7f8ff",
    borderColor: palette.accent,
  },
  categoryMeta: {
    flex: 1,
    minWidth: 0,
  },
  categoryBadge: {
    color: palette.accent,
    fontWeight: "800",
  },
  checkbox: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 6,
    borderWidth: 1,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  checkboxSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  checkboxText: {
    color: palette.accent,
    fontWeight: "700",
  },
  rowText: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "700",
  },
  rowDetail: {
    color: palette.muted,
    fontSize: 13,
  },
  monthGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  monthChip: {
    alignItems: "center",
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flexGrow: 1,
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 12,
    width: "31.5%",
  },
  monthChipSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  monthChipText: {
    color: palette.text,
    fontWeight: "800",
    textAlign: "center",
  },
  monthChipTextSelected: {
    color: "#fff",
  },
  yearList: {
    gap: 8,
  },
  yearRow: {
    alignItems: "center",
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  yearRowSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  yearRowText: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  yearRowTextSelected: {
    color: "#fff",
  },
  input: {
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    color: palette.text,
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 11,
    backgroundColor: "#fff",
  },
  formError: {
    color: palette.danger,
    fontWeight: "700",
  },
  submitButton: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 14,
    minHeight: 48,
    justifyContent: "center",
    paddingVertical: 13,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  submitButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  previewRow: {
    color: palette.text,
    lineHeight: 20,
  },
  actionRow: {
    flexDirection: "row",
    gap: 8,
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  secondaryButtonText: {
    color: palette.accent,
    fontWeight: "800",
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: "#b42318",
    borderRadius: 14,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
  },
  dangerButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
});

export const sendCommunicationStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  panel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  title: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
  },
  sectionTitle: {
    color: "#1f1f1d",
    fontSize: 18,
    fontWeight: "700",
  },
  field: {
    gap: 6,
  },
  label: {
    color: "#4c4c47",
    fontSize: 13,
    fontWeight: "700",
  },
  fieldError: {
    color: "#b42318",
    fontSize: 12,
  },
  input: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#1f1f1d",
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  textArea: {
    minHeight: 132,
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  segmentButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  segmentButtonActive: {
    backgroundColor: "#5f6df5",
    borderColor: "#5f6df5",
  },
  segmentText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  segmentTextActive: {
    color: "#fff",
  },
  modeButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    minWidth: 86,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  modeButtonActive: {
    backgroundColor: "#e4e7ff",
    borderColor: "#5f6df5",
  },
  modeText: {
    color: "#3d3d39",
    fontWeight: "700",
  },
  modeTextActive: {
    color: "#5f6df5",
  },
  loading: {
    alignItems: "center",
    gap: 8,
    padding: 22,
  },
  loadingText: {
    color: "#666",
  },
  infoBox: {
    backgroundColor: "#f7f8ff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  infoTitle: {
    color: "#1f1f1d",
    fontWeight: "700",
  },
  infoDetail: {
    color: "#5c5c56",
  },
  selector: {
    gap: 10,
  },
  selectionCount: {
    color: "#5c5c56",
    fontSize: 13,
    fontWeight: "700",
  },
  list: {
    gap: 8,
  },
  row: {
    alignItems: "center",
    borderColor: "#e8ecff",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 10,
  },
  categoryBlock: {
    borderColor: "#e8ecff",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  categoryHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    padding: 10,
  },
  categoryTitleButton: {
    flex: 1,
    minWidth: 0,
  },
  categoryUsers: {
    borderTopColor: "#e8ecff",
    borderTopWidth: 1,
    gap: 7,
    padding: 10,
  },
  categoryUserRow: {
    alignItems: "center",
    borderColor: "#e8ecff",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    padding: 8,
  },
  categoryUserRowSelected: {
    backgroundColor: "#f7f8ff",
    borderColor: "#b8cec8",
  },
  rowSelected: {
    backgroundColor: "#f7f8ff",
    borderColor: "#5f6df5",
  },
  checkbox: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 6,
    borderWidth: 1,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  checkboxText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  smallCheckbox: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 6,
    borderWidth: 1,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  rowText: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
  },
  rowDetail: {
    color: "#676760",
    fontSize: 13,
  },
  formError: {
    color: "#b42318",
  },
  submitButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    minHeight: 48,
    justifyContent: "center",
    paddingVertical: 13,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  submitButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  checkboxSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
});

export const planAttendanceStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  hero: {
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  kicker: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  title: {
    color: palette.text,
    fontSize: 26,
    fontWeight: "800",
  },
  subtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  deniedBox: {
    gap: 8,
    padding: 16,
  },
  panel: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 22,
    borderWidth: 1,
    padding: 14,
  },
  panelHeader: {
    gap: 4,
  },
  panelHint: {
    color: palette.muted,
    fontSize: 12,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 8,
  },
  muted: {
    color: palette.muted,
    lineHeight: 20,
  },
  errorText: {
    color: palette.danger,
    marginTop: 10,
    fontWeight: "700",
  },
  successText: {
    color: palette.success,
    marginTop: 10,
    fontWeight: "700",
  },
  shiftList: {
    gap: 10,
  },
  attendanceCard: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  attendanceTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  attendanceTime: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  typeChip: {
    borderRadius: 999,
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  typeChipIn: {
    backgroundColor: palette.success,
  },
  typeChipOut: {
    backgroundColor: palette.warning,
  },
  shiftMeta: {
    color: palette.muted,
  },
  shiftActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  miniButton: {
    alignItems: "center",
    borderColor: palette.accent,
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    minHeight: 36,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  miniButtonText: {
    color: palette.accent,
    fontWeight: "800",
  },
  dangerButton: {
    alignItems: "center",
    borderColor: "#efc0ba",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    minHeight: 36,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  dangerButtonText: {
    color: palette.danger,
    fontWeight: "800",
  },
  label: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 8,
    marginTop: 14,
    textTransform: "uppercase",
  },
  chipsRow: {
    gap: 8,
    paddingRight: 12,
  },
  shiftChip: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 2,
    minHeight: 58,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    width: 220,
  },
  shiftChipSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  shiftChipText: {
    color: palette.text,
    fontWeight: "800",
  },
  shiftChipTextSelected: {
    color: "#fff",
  },
  shiftChipMeta: {
    color: palette.muted,
    fontSize: 11,
  },
  controlsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  typeButton: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 42,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  typeButtonSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  typeButtonText: {
    color: palette.accent,
    fontWeight: "800",
  },
  typeButtonTextSelected: {
    color: "#fff",
  },
  formGrid: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 14,
    flexGrow: 1,
    minHeight: 46,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flexGrow: 1,
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 12,
    backgroundColor: "#fff",
  },
  secondaryButtonText: {
    color: palette.accent,
    fontWeight: "800",
  },
  disabled: {
    opacity: 0.65,
  },
});

export const authStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
    gap: 18,
  },
  card: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  cardHeader: {
    gap: 4,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "900",
  },
  cardSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  button: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 16,
    minHeight: 52,
    justifyContent: "center",
    marginTop: 4,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  forgotButton: {
    alignItems: "center",
    paddingVertical: 4,
  },
  forgotText: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "600",
  },
  error: {
    backgroundColor: "#fff1f0",
    borderColor: "#f0b8af",
    borderRadius: 14,
    borderWidth: 1,
    color: palette.danger,
    fontWeight: "700",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
});

export const forgotPasswordStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
    gap: 18,
  },
  card: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  cardHeader: {
    gap: 4,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "900",
  },
  cardSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  button: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 16,
    minHeight: 52,
    justifyContent: "center",
    marginTop: 4,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  backButton: {
    alignItems: "center",
    paddingVertical: 4,
  },
  backText: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "600",
  },
  error: {
    backgroundColor: "#fff1f0",
    borderColor: "#f0b8af",
    borderRadius: 14,
    borderWidth: 1,
    color: palette.danger,
    fontWeight: "700",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  successContainer: {
    alignItems: "center",
    gap: 14,
    paddingVertical: 8,
  },
  successIcon: {
    alignItems: "center",
    backgroundColor: "#f0f7ff",
    borderRadius: 50,
    height: 72,
    justifyContent: "center",
    width: 72,
  },
  successIconText: {
    fontSize: 32,
  },
});

export const resetPasswordStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
    gap: 18,
  },
  card: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  cardHeader: {
    gap: 4,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "900",
  },
  cardSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  button: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 16,
    minHeight: 52,
    justifyContent: "center",
    marginTop: 4,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  error: {
    backgroundColor: "#fff1f0",
    borderColor: "#f0b8af",
    borderRadius: 14,
    borderWidth: 1,
    color: palette.danger,
    fontWeight: "700",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  requirementsContainer: {
    backgroundColor: "#f8f9ff",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  requirementRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
  },
  requirementDot: {
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  requirementDotMet: {
    backgroundColor: "#22c55e",
  },
  requirementDotUnmet: {
    backgroundColor: "#d1d5db",
  },
  requirementText: {
    fontSize: 11,
    fontWeight: "600",
  },
  requirementTextMet: {
    color: "#16a34a",
  },
  requirementTextUnmet: {
    color: palette.muted,
  },
  successContainer: {
    alignItems: "center",
    gap: 14,
    paddingVertical: 8,
  },
  successIcon: {
    alignItems: "center",
    backgroundColor: "#f0f7ff",
    borderRadius: 50,
    height: 72,
    justifyContent: "center",
    width: 72,
  },
  successIconText: {
    fontSize: 32,
  },
});

export const dashboardStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  hero: {
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  kicker: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  title: {
    color: palette.text,
    fontSize: 26,
    fontWeight: "800",
  },
  subtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  panel: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  panelHeader: {
    gap: 4,
  },
  panelTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 12,
  },
  panelHint: {
    color: palette.muted,
    fontSize: 12,
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  nextShiftTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 8,
  },
  nextShiftMeta: {
    color: palette.muted,
    marginTop: 4,
  },
  clockButton: {
    alignItems: "center",
    backgroundColor: palette.accent,
    borderRadius: 14,
    marginTop: 12,
    minHeight: 48,
    justifyContent: "center",
  },
  clockButtonDisabled: {
    opacity: 0.7,
  },
  clockButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
  muted: {
    color: palette.muted,
    lineHeight: 20,
    marginTop: 12,
  },
  successText: {
    color: palette.success,
    marginTop: 8,
    fontWeight: "700",
  },
  errorText: {
    color: palette.danger,
    marginTop: 8,
    fontWeight: "700",
  },
  weekControls: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
    marginTop: 12,
  },
  smallButton: {
    alignItems: "center",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  smallButtonText: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  weekCalendar: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 6,
    marginTop: 12,
  },
  weekDayCard: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
    flex: 1,
    minWidth: 0,
    padding: 8,
  },
  weekDayTitle: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  weekDayCount: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  weekShiftChip: {
    backgroundColor: "#fff",
    borderColor: palette.border,
    borderRadius: 10,
    borderWidth: 1,
    gap: 2,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  weekShiftChipTime: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "800",
  },
  weekShiftChipStatus: {
    color: palette.muted,
    fontSize: 10,
  },
  weekShiftMore: {
    color: palette.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  dayBlock: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  dayTitle: {
    color: palette.text,
    fontWeight: "800",
  },
  shiftItem: {
    backgroundColor: "#fff",
    borderColor: palette.border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  shiftTime: {
    color: palette.text,
    fontWeight: "800",
  },
  shiftMeta: {
    color: palette.muted,
    fontSize: 12,
  },
  weekDayCardSelected: {
    borderColor: palette.accent,
    backgroundColor: "#eaf2ff",
    transform: [{ scale: 1.02 }],
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },

  shiftList: {
    gap: 10,
    marginTop: 10,
  },

  shiftCard: {
    backgroundColor: "#fff",
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  }
});

export const contactsStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
  },
  filtersPanel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  filterField: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  filterLabel: {
    color: "#4c4c47",
    fontSize: 13,
    fontWeight: "700",
  },
  input: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    color: "#1f1f1d",
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  filtersRow: {
    flexDirection: "row",
    gap: 10,
  },
  actions: {
    flexDirection: "row",
    gap: 10,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  loading: {
    alignItems: "center",
    gap: 8,
    padding: 28,
  },
  loadingText: {
    color: "#666",
  },
  list: {
    gap: 10,
  },
  userCard: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
  },
  userMain: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  userName: {
    color: "#1f1f1d",
    flex: 1.25,
    fontSize: 15,
    fontWeight: "700",
    minWidth: 0,
  },
  userCategory: {
    color: "#63635e",
    flex: 1,
    fontSize: 13,
    minWidth: 0,
  },
  userRole: {
    color: "#5f6df5",
    fontSize: 12,
    fontWeight: "700",
    minWidth: 62,
    textAlign: "right",
  },
  userDetails: {
    borderTopColor: "#e8ecff",
    borderTopWidth: 1,
    gap: 4,
    marginTop: 10,
    paddingTop: 10,
  },
  detailActionRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  detailText: {
    color: "#3d3d39",
    flex: 1,
    fontSize: 14,
    minWidth: 0,
  },
  detailActionButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
});

export const myScheduleStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  hero: {
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  kicker: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  title: {
    color: palette.text,
    fontSize: 26,
    fontWeight: "800",
  },
  subtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  panel: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  panelHeader: {
    gap: 4,
  },
  panelHint: {
    color: palette.muted,
    fontSize: 12,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
  },
  shiftList: {
    gap: 10,
  },
  shiftCard: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  shiftTop: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  shiftTime: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  shiftMeta: {
    color: palette.muted,
  },
  badge: {
    backgroundColor: "#e6f1ec",
    borderRadius: 999,
    color: palette.success,
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeDraft: {
    backgroundColor: "#eef3ff",
    color: palette.warning,
  },
  muted: {
    color: palette.muted,
    lineHeight: 20,
  },
  weekCalendar: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 6,
    marginTop: 12,
  },
  weekDayCard: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
    flex: 1,
    minWidth: 0,
    padding: 8,
  },
  weekDayTitle: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  weekDayCount: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  weekShiftChip: {
    backgroundColor: "#fff",
    borderColor: palette.border,
    borderRadius: 10,
    borderWidth: 1,
    gap: 2,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  weekShiftChipTime: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "800",
  },
  weekShiftChipStatus: {
    color: palette.muted,
    fontSize: 10,
  },
  weekShiftMore: {
    color: palette.accent,
    fontSize: 11,
    fontWeight: "700",
  },
});

export const myAttendanceStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  hero: {
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  kicker: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  title: {
    color: palette.text,
    fontSize: 26,
    fontWeight: "800",
  },
  subtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  panel: {
    backgroundColor: palette.surfaceElevated,
    borderColor: palette.border,
    borderRadius: 22,
    borderWidth: 1,
    padding: 14,
  },
  panelHeader: {
    gap: 4,
  },
  panelHint: {
    color: palette.muted,
    fontSize: 12,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 8,
  },
  list: {
    gap: 10,
  },
  card: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  cardTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  typeChip: {
    borderRadius: 999,
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  typeChipIn: {
    backgroundColor: palette.success,
  },
  typeChipOut: {
    backgroundColor: palette.warning,
  },
  time: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  meta: {
    color: palette.muted,
  },
  muted: {
    color: palette.muted,
    lineHeight: 20,
  },
  weekSummary: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 6,
  },
  weekSummaryItem: {
    backgroundColor: palette.backgroundSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    flex: 1,
    minWidth: 0,
    padding: 12,
  },
  weekSummaryDay: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "800",
  },
  weekSummaryCount: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  navButton: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 40,
    minWidth: 86,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  monthCenter: {
    flex: 1,
    gap: 2,
  },
  todayButton: {
    alignItems: "center",
    alignSelf: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  todayButtonText: {
    color: palette.accent,
    fontWeight: "800",
  },
});

export const profileStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 96,
  },
  header: {
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
  },
  name: {
    color: "#151515",
    fontSize: 24,
    fontWeight: "700",
    textAlign: "center",
  },
  meta: {
    color: "#676760",
    fontSize: 15,
  },
  panel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  panelTitle: {
    color: "#151515",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 12,
  },
  fab: {
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    bottom: 24,
    elevation: 4,
    paddingHorizontal: 18,
    paddingVertical: 14,
    position: "absolute",
    right: 16,
    shadowColor: "#000",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },
  fabText: {
    color: "#fff",
    fontWeight: "700",
  },
  modalOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: "90%",
  },
  modalContent: {
    gap: 14,
    padding: 16,
    paddingBottom: 28,
  },
  modalTitle: {
    color: "#151515",
    fontSize: 20,
    fontWeight: "700",
  },
  photoEditor: {
    alignItems: "center",
    gap: 12,
  },
  photoActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
  },
  secondaryButton: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: "#5f6df5",
    fontWeight: "700",
  },
  error: {
    color: "#b42318",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "flex-end",
  },
  cancelButton: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  cancelButtonText: {
    color: "#3d3d39",
    fontWeight: "700",
  },
  saveButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 8,
    minWidth: 92,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
});

export const bandejaStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#eef3ff",
    flex: 1,
  },
  content: {
    gap: 16,
    padding: 16,
    paddingBottom: 132,
  },
  headerPanel: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 14,
  },
  title: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
  },
  countsRow: {
    flexDirection: "row",
    gap: 8,
  },
  countBox: {
    backgroundColor: "#f7f8ff",
    borderColor: "#e4e7ff",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    padding: 10,
  },
  countValue: {
    color: "#5f6df5",
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  countLabel: {
    color: "#62625c",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  loading: {
    alignItems: "center",
    gap: 8,
    padding: 28,
  },
  loadingText: {
    color: "#666",
  },
  list: {
    gap: 10,
  },
  card: {
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  cardSelectable: {
    borderStyle: "dashed",
  },
  cardSelected: {
    backgroundColor: "#f7f4ff",
    borderColor: "#5f6df5",
  },
  cardUnread: {
    borderColor: "#5f6df5",
  },
  cardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  cardTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  cardTitle: {
    color: "#1f1f1d",
    fontSize: 16,
    fontWeight: "700",
  },
  sender: {
    color: "#64645e",
    fontSize: 13,
  },
  typePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  typeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  checkbox: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#c9d0ff",
    borderRadius: 999,
    borderWidth: 1,
    height: 22,
    justifyContent: "center",
    marginLeft: 2,
    width: 22,
  },
  checkboxSelected: {
    backgroundColor: "#5f6df5",
    borderColor: "#5f6df5",
  },
  checkboxText: {
    color: "#5f6df5",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 14,
  },
  checkboxTextSelected: {
    color: "#fff",
  },
  preview: {
    color: "#393934",
    fontSize: 14,
    lineHeight: 20,
  },
  metaRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  dateText: {
    color: "#75756e",
    flex: 1,
    fontSize: 12,
  },
  readState: {
    color: "#6a6a64",
    fontSize: 12,
    fontWeight: "700",
  },
  unreadState: {
    color: "#5f6df5",
  },
  detailLoading: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    bottom: 0,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  modalOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: "88%",
  },
  modalContent: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
  xButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  xButtonText: {
    color: "#2f2f2b",
    fontWeight: "700",
  },
  detailHeader: {
    gap: 6,
  },
  detailTitle: {
    color: "#151515",
    fontSize: 22,
    fontWeight: "700",
  },
  detailSender: {
    color: "#4c4c47",
    fontSize: 14,
  },
  detailDate: {
    color: "#75756e",
    fontSize: 13,
  },
  detailBody: {
    borderColor: "#d7ddff",
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  detailContent: {
    color: "#222",
    fontSize: 16,
    lineHeight: 23,
  },
  selectionBar: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#d7ddff",
    borderRadius: 14,
    borderWidth: 1,
    bottom: 88,
    flexDirection: "row",
    gap: 12,
    left: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: "absolute",
    right: 16,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  selectionText: {
    color: "#1f1f1d",
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
  },
  selectionActions: {
    flexDirection: "row",
    gap: 8,
  },
  cancelSelectionButton: {
    alignItems: "center",
    borderColor: "#d7ddff",
    borderRadius: 10,
    borderWidth: 1,
    minWidth: 88,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  cancelSelectionText: {
    color: "#3d3d39",
    fontWeight: "700",
  },
  confirmSelectionButton: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 10,
    minWidth: 88,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  confirmSelectionButtonDisabled: {
    opacity: 0.8,
  },
  confirmSelectionText: {
    color: "#fff",
    fontWeight: "700",
  },
  fabContainer: {
    bottom: 24,
    position: "absolute",
    right: 16,
  },
  fab: {
    alignItems: "center",
    backgroundColor: "#5f6df5",
    borderRadius: 999,
    elevation: 4,
    minWidth: 112,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: "#000",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },
  fabDisabled: {
    opacity: 0.45,
  },
  fabText: {
    color: "#fff",
    fontWeight: "700",
  },
});
